name = "hono-chat-app"
main = "src/index.js"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "chat_db"
database_id = "2c15e94a-32ca-4384-8532-926c72a51eee"

[vars]
JWT_SECRET = "my-super-secret-jwt-key-2024-change-this"